trigger:
  branches:
    include:
      - main

variables:
  ## Import variables from library variable group named Common
  - group: Common
  ## C# project file name, to be used when compiling Function App code
  - name: webAppPath
    value: "teknologisk_functionapp.csproj"
  ## Build configuration. Should be Debug / Release build
  - name: buildConfiguration
    value: Debug
pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      ## Build the Function App code and add to DevOps pipeline
      - job: Job_1
        displayName: "Build and publish code"
        steps:
          - checkout: self

          - task: DotNetCoreCLI@2
            displayName: "Publish/Build Web App - $(buildConfiguration)"
            inputs:
              command: "publish"
              projects: $(webAppPath)
              publishWebProjects: false
              arguments: "-o $(Build.ArtifactStagingDirectory)/WebApp --configuration $(buildConfiguration)"

          - task: PublishPipelineArtifact@1
            displayName: "Publish Web App to Pipeline"
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)/WebApp"
              artifact: WebApp
              publishLocation: "pipeline"

  ## Run deploy.yaml file for Test environment. Uses ResourceGroupName, test.Connection, AppName from Common library variable group in DevOps
  - template: deploy.yaml
    parameters:
      ResourceGroupName: $(ResourceGroupName)
      EnvironmentPostFix: test
      ## This is the Service Connection name. This can be created in DevOps under Project.
      ServiceConnection: $(test.connection)
      AppName: $(AppName)
      Location: westeurope

  - template: deploy.yaml
    parameters:
      ResourceGroupName: $(ResourceGroupName)
      EnvironmentPostFix: prod
      ServiceConnection: $(prod.connection)
      AppName: $(AppName)
      Location: westeurope
