## These are parameters sent from the build.yaml file
parameters:
  - name: EnvironmentPostFix
    type: string
  - name: ServiceConnection 
    type: string
  - name: ResourceGroupName
    type: string

  - name: AppName
    type: string
  - name: Location
    type: string

stages:
  - stage: ${{ parameters.EnvironmentPostFix }}Release
    variables:
      ## The name of the resource group, where the function app should be deployed to.
      - name: resourceGroup
        value: ${{ parameters.ResourceGroupName }}-rg
      - name: webAppName
        value: ${{ parameters.AppName }}
    displayName: Release to ${{ parameters.EnvironmentPostFix }}
    jobs:
      - deployment: ${{ parameters.EnvironmentPostFix }}
        displayName: Release to ${{ parameters.EnvironmentPostFix }}
        environment: ${{ parameters.EnvironmentPostFix }}
        strategy:
          runOnce:
            deploy:
              ## Deploy the Function App using the built in Azure Pipeline Task named AzureFunctionApp@2
              steps:
                - task: AzureFunctionApp@2
                  displayName: "Publish Function App to Azure"
                  inputs:
                    azureSubscription: ${{ parameters.ServiceConnection }}
                    appType: "functionApp"
                    appName: $(webAppName)
                    package: "$(Pipeline.Workspace)/WebApp/*.zip"
